# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: 
      - nuget

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          nugetfeed="github"
          nugetsource="https://nuget.pkg.github.com/soccerjoshj07/index.json"
          username="soccerjoshj07"
          pat="${{ secrets.PAT}}"

          # adding to ~/.config/NuGet/NuGet.config
          nuget sources add -Name $nugetfeed -Source $nugetsource -username $username -password $pat 

          results=$(find . -name "*.nupkg")
          resultsArray=($results)

          #echo "${resultsArray[*]}"

          for var in "${resultsArray[@]}"
          do
              echo $var
              nuget push -Source $nugetfeed -ApiKey az $var
          done
