# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish NuGet Package

on:
  push:
    branches: 
      - nuget

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: nuget push
        run: |
          nugetfeed="github"
          nugetsource="https://nuget.pkg.github.com/soccerjoshj07/index.json"
          username="soccerjoshj07"

          # adding to ~/.config/NuGet/NuGet.config
          nuget sources add -Name $nugetfeed -Source $nugetsource -username $username -password ${{ secrets.GITHUB_TOKEN }}
          # nuget setapikey ${{ secrets.GITHUB_TOKEN }} -source $nugetsource

          results=$(find . -name "*.nupkg")
          resultsArray=($results)

          #echo "${resultsArray[*]}"

          for var in "${resultsArray[@]}"
          do
              echo $var
              nuget push -Source $nugetfeed -ApiKey $${{ secrets.GITHUB_TOKEN }} $var
          done

      # - uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      #   with:
      #     nupkg-path:  '*.nupkg'
      #     repo-owner:  'soccerjoshj07'
      #     gh-user:  'soccerjoshj07'
      #     token:  ${{ secrets.GITHUB_TOKEN }}
